version: '3'
services:
  app:
    profiles: ['devcontainer']
    container_name: skku-royals-recruiting
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:20-bullseye
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    environment:
      DEVCONTAINER: 1
