name: CD

on:
  push:
    branches: [master]

jobs:
  deploy-to-s3:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [19]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Cache dist
        uses: actions/cache@v3
        with:
          path: ./*/dist
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-${{ github.sha }}-survey

      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_S3_SECRET_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}'
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            frontend/survey/dist s3://recruiting.skku-royals.football
